\documentclass{beamer}
\usecolortheme{seahorse}

\title{What is Beamer?}
\subtitle{STAT 4870}
\author{Erin Kreiling}
\institute{Appalachian State University\\
  Boone, North Carolina\\[1ex]
  }
\date{February 25, 2014}

\begin{document}

%--- the titlepage frame -------------------------%
\begin{frame}[plain]
  \titlepage
\end{frame}

%--- the presentation begins here ----------------%
\begin{frame}{Overview}
  Overview of the material.
\end{frame}

\end{document}